### ISSUE TITLE
SQL Injection vulnerability

### ISSUE THREAD

**Issue by architect-sdk** [LandisGames/impulse#9]
(Not sure if it's truly SQL Injectible but check it out)
In file sv_net in line 97 and 129 there's no sanitization or validation of the query nor any prepared query statement, someone can just input character name containing a SQL injection payload (e.g. ' or 1=1 --')

`local charName = net.ReadString()`
`insertQuery:Insert("rpname", charName)`

**Comment by NforceSSP** [comment]
impulse sanitizes the string by both limiting the character count and removing any unnecessary characters, for example ` and _.
(in core/sh_name.lua lines 41 to 46)
```lua
if name:len() >= 24 then
	return false, "Name too long. (max. 24)" 
end

name = name:Trim()
name = impulse.SafeString(name)
```
so, any actual sql attacks would either be too long or the name would be sanitized before it could do anything.
